export const games = [
  {
    id: 1,
    title: "view finder",
    poster: "/images/viewfinder.jpg",
    price: 125000,
    platform: ["windows"],
    genres: ["adventure", "puzzle"],
  },
  {
    id: 2,
    title: "valheim",
    poster: "/images/valheim.jpg",
    price: 115000,
    platform: ["windows"],
    genres: ["adventure", "survival", "rpg"],
  },
  {
    id: 3,
    title: "terraria",
    poster: "/images/terraria.jpg",
    price: 75000,
    platform: ["windows", "playstation", "xbox", "android"],
    genres: ["adventure", "survival", "rpg"],
  },
  {
    id: 4,
    title: "super liminal",
    poster: "/images/superliminal.jpg",
    price: 150000,
    platform: ["windows", "playstation", "xbox"],
    genres: ["Puzzle"],
  },
  {
    id: 5,
    title: "subnautica",
    poster: "/images/subnautica.jpg",
    price: 175000,
    platform: ["windows", "playstation"],
    genres: ["adventure", "survival"],
  },
  {
    id: 6,
    title: "stardew valley",
    poster: "/images/stardew_valley.jpg",
    price: 75000,
    platform: ["windows", "playstation", "nintendo", "xbox"],
    genres: ["simulation"],
  },
  {
    id: 7,
    title: "sea of thieves",
    poster: "/images/sot.jpeg",
    price: 200000,
    platform: ["windows", "playstation", "xbox"],
    genres: ["adventure"],
  },
  {
    id: 8,
    title: "resident evil 4",
    poster: "/images/re4.jpg",
    price: 500000,
    platform: ["windows", "playstaion"],
    genres: ["horror", "survival"],
  },
  {
    id: 9,
    title: "palworld",
    poster: "/images/palworld.jpg",
    price: 300000,
    platform: ["windows"],
    genres: ["adventure", "survival", "rpg"],
  },
  {
    id: 10,
    title: "octopath traveller 1",
    poster: "/images/ot1.jpg",
    price: 700000,
    platform: ["windows", "nintendo", "xbox", "android", "playstation"],
    genres: ["adventure", "rpg"],
  },
  {
    id: 11,
    title: "minecraft",
    poster: "/images/minecraft.webp",
    price: 200000,
    platform: ["windows", "nintendo", "playstation", "xbox", "android"],
    genres: ["adventure", "survival", "sandbox"],
  },
  {
    id: 12,
    title: "lethal company",
    poster: "/images/lethal_company.jpg",
    price: 100000,
    platform: ["windows"],
    genres: ["survival", "horror"],
  },
  {
    id: 13,
    title: "five night at fredy 1",
    poster: "/images/fnaf.jpg",
    price: 50000,
    platform: ["windows"],
    genres: ["horror"],
  },
  {
    id: 14,
    title: "enshrouded",
    poster: "/images/enshrouded.jpg",
    price: 250000,
    platform: ["windows"],
    genres: ["adventure", "survival", "rpg"],
  },
  {
    id: 15,
    title: "coffe talk",
    poster: "/images/coffe_talk.jpg",
    price: 250000,
    platform: ["windows", "nintendo", "playstation"],
    genres: ["casual"],
  },
  {
    id: 16,
    title: "a space for the unbound",
    poster: "/images/a_space_for_the_un_bound.jpg",
    price: 200000,
    platform: ["windows", "xbox", "nintendo"],
    genres: ["rpg"],
  },
  {
    id: 17,
    title: "hello neighbor 2",
    poster: "/images/hn2.jpg",
    price: 150000,
    platform: ["windows", "xbox", "nintendo"],
    genres: ["horror", "puzzle"],
  },
];
